### ISSUE TITLE
use good output names since they will be consumed by users in workflows

### ISSUE THREAD

**Issue by bryanmacfarlane** [romil07/actions#3]
So, you don't want names like `secret1`: https://github.com/romil07/actions/blob/master/KeyVault-GetSecrets/action.yml#L11

in some future step, this would have users doing:
```yaml
- use: ./some/other/action
  with:
      myInput: steps.keyvault.outputs.secret1
```

You probably want something like `secret` or `keyvault-secret`
